# The median of independent repeated  sampling

In [15]:
%pylab inline

import numpy as np
import random

Populating the interactive namespace from numpy and matplotlib


## The median of a distribution

The median of a distribution $P$ is the value $m$ such that if $X\sim P$, then $P(X\le m)\ge\frac12$ and  $P(X\ge m)\ge\frac12$. If multiple values satisfy this condition, the median is their average.

For example, for the biased die with distribution given by
<table>
<tr><th>x</th><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td></tr>
<tr><th>$P_X$(x)</th><td>0.1</td><td>0.2</td><td>0.1</td><td>0.3</td><td>0.1</td><td>0.2</td></tr>
</table>
Since $P(X\le 4)=0.7\ge 0.5$ and $P(X\ge 4)=0.6\ge 0.5$, $m=4$.

If the distribution was,
<table>
<tr><th>x</th><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td></tr>
<tr><th>$P_X$(x)</th><td>0.1</td><td>0.2</td><td>0.2</td><td>0.2</td><td>0.1</td><td>0.2</td></tr>
</table>
then both 3 and 4 satisfy the two conditions, and the median is 3.5. 

While writing the following functions, note that the distribution $P=[x_1,\ldots x_k]$ represents $P_X(1)=x_1,\ldots,P_X(k)=x_k$.

### Exercise 1

Write a function <code><font color="blue">median_cal</font>(P)</code> that returns the median given a distribution <code>P</code>.

<font color="blue">* **Sample run** *</font>
```python
print(median_cal([0.1 0.2 0.1 0.3 0.1 0.2]))
print(median_cal([0.99 0.01])
```
<font color="magenta">* **Expected Output** *</font>
```python
4
1
```

In [8]:
def median_cal(P):
    total = 0
    for i, val in enumerate(P, 1):
        total += val
        if total > 0.5:
            return i
        elif total == 0.5:
            return (2 * i + 1)/2
        
median_cal([0.12,0.04,0.12,0.12,0.2,0.16,0.16,0.08])

5

In [7]:
#Check Function

assert median_cal([0.99,0.1])==1
assert median_cal([0.1,0.2,0.1,0.3,0.1,0.2])==4


## Median of a sample 

If the distribution is given, as above, the median can be determined easily. In this problem we will learn how to approximate the median when the distribution is not given, but we are given samples that it generates. 

Similar to distributions, we can define the median of a set to be the set element $m'$ such that at least half the elements in the set are $\le m'$ and at least half the numbers in the collection are $\ge m'$. If two set elements satisfy this condition, then the median is their average. For example, the median of [3,2,5,5,2,4,1,5,4,4] is $4$ and the median of [2,1,5,3,3,5,4,2,4,5] is $3.5$.

To find the median of a $P$ distribution via access only to samples
it generates, we obtain $n$ samples from $P$, caluclate their median 
$M_n$, and then repeat the process many times and determine the average
of all the medians. 

### Exercise 2

Write a function <code><font color="blue">sample_median</font>(n,P)</code> that generates <code>n</code> random values using distribution <code>P</code> and returns the median of the collected sample.

Hint: Use function <b>random.choice()</b> to sample data from <code>P</code> and <b>median()</b> to find the median of the samples

<font color="blue">* **Sample run** *</font>
```python
print(sample_median(10,[0.1 0.2 0.1 0.3 0.1 0.2])) 
print(sample_median(10,[0.1 0.2 0.1 0.3 0.1 0.2]))
print(sample_median(5,P=[0.3,0.7])
print(sample_median(5,P=[0.3,0.7])
```
<font color="magenta">* **Expected Output** *</font>
```python
4.5
4.0
2.0
1.0
```



In [14]:
np.median([2,1,5,3,3,5,4,2,4,5])

3.5

In [45]:
def sample_median(n,P):
    distribution = []
    for i in range(n):
        distribution.append(random.choices(range(1, len(P) + 1), weights = P))
    return np.median(distribution)

medians = []
for i in range(25):
    medians.append(sample_median(10, [0.1, 0.2, 0.1, 0.3, 0.1, 0.2]))
print(np.unique(medians, return_counts = True))

medians = []
for i in range(25):
    medians.append(sample_median(5, [0.3, 0.7]))
print(np.unique(medians, return_counts = True))

for n in range(1, 26):
    answer_medians = []
    for j in range(100):
        answer_medians.append(sample_median(n, [0.12,0.04,0.12,0.12,0.2,0.16,0.16,0.08]))
    print('\nAnswer for (n = ' + str(n) + '): \n' + str(np.unique(answer_medians, return_counts = True)))

(array([3. , 3.5, 4. , 4.5, 5. ]), array([ 4,  1, 17,  1,  2]))
(array([1., 2.]), array([ 3, 22]))

Answer for (n = 1): 
(array([1., 2., 3., 4., 5., 6., 7., 8.]), array([12,  3,  7, 13, 26, 19, 17,  3]))

Answer for (n = 2): 
(array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5]), array([ 2,  3,  6, 10,  7, 10, 11, 17, 13,  8, 10,  1,  2]))

Answer for (n = 3): 
(array([1., 2., 3., 4., 5., 6., 7., 8.]), array([ 2,  3, 16, 21, 32, 19,  4,  3]))

Answer for (n = 4): 
(array([1. , 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5]), array([ 1,  1,  4,  7,  7, 13,  8, 11, 23, 12,  4,  7,  2]))

Answer for (n = 5): 
(array([1., 3., 4., 5., 6., 7.]), array([ 2, 10, 20, 37, 21, 10]))

Answer for (n = 6): 
(array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5]), array([ 1,  1,  2,  4, 10, 16, 18, 22, 15,  3,  6,  2]))

Answer for (n = 7): 
(array([2., 3., 4., 5., 6., 7.]), array([ 2, 11, 22, 38, 22,  5]))

Answer for (n = 8): 
(array([3. , 4. , 4.5, 5. 

In [37]:
#Check Function

assert abs(sample_median(10,[0.1,0.2,0.3,0.2,0.2])-3)<=1
assert abs(sample_median(25,[0.2,0.1,0.2,0.3,0.1,0.1])-3)<=1


### Exercise 3 

Write a function <code><font color="blue">expected_cal</font>(P)</code> that finds the expected value of the distribution P.

In [48]:
def expected_cal(P):
    total = 0
    for i, j in enumerate(P, start = 1):
        total += (i * j)
    return total

print(expected_cal([0.25,0.25,0.25,0.25]))
print(expected_cal([0.3,0.4,0.3]))
print(expected_cal([0.12, 0.04, 0.12, 0.12, 0.2, 0.16, 0.16, 0.08]))

2.5
2.0
4.76


In [47]:
#Check function

assert expected_cal([0.25,0.25,0.25,0.25])==2.5
assert expected_cal([0.3,0.4,0.3])==2

### Exercise 4

In this exercise, we explore the relationship between the distribution median $m$, the sample median with $n$ samples, and $E[M_n]$,the expected value of $M_n$. 

Write a function <code><font color="blue">average_sample_median</font>(n,P)</code>, that return the average $M_n$ of 1000 samples of size <code>n</code> sampled from the distribution <code>P</code>.

<font color="blue">* **Sample run** *</font>
```python
print(average_sample_median(10,[0.2,0.1,0.15,0.15,0.2,0.2])) 
print(average_sample_median(10,[0.3,0.4,0.3]))
print(average_sample_median(10,P=[0.99,0.01])
```
<font color="magenta">* **Expected Output** *</font>
```python
3.7855
2.004
1
```

In [52]:
np.unique(answer_medians, return_counts = True)[1]

array([ 1,  8, 75, 16])

In [61]:
def average_sample_median(n,P):
    answer_medians = []
    for i in range(1000):
        answer_medians.append(sample_median(n, P))
    unique, counts = np.unique(answer_medians, return_counts = True)
    return np.average(unique, weights = counts)

print(average_sample_median(10, [0.2, 0.1, 0.15, 0.15, 0.2, 0.2]))
print(average_sample_median(10, [0.3,0.4,0.3]))
print(average_sample_median(10, [0.99,0.01]))
print('Answer: ' + str(average_sample_median(100,[0.12, 0.04, 0.12, 0.12, 0.2, 0.16, 0.16, 0.08])))

3.814
2.0005
1.0
Answer: 4.997


In [59]:
#Check function
assert((average_sample_median(20,[0.4,0.6])-median_cal([0.4,0.6]))<=1e-3)
assert((average_sample_median(200,[0.1,0.2,0.3,0.1,0.1,0.2])-median_cal([0.1,0.2,0.3,0.1,0.1,0.2]))<=1)

In [62]:
print('Q5 comparison: ' + str(average_sample_median(1,[0.12, 0.04, 0.12, 0.12, 0.2, 0.16, 0.16, 0.08])))

Q5 comparison: 4.79
